export const SET_CHAMPION="SET_CHAMPION"

export const championsArray=[
    {id:1,name:"Aatrox"},
    {id:2,name:"Ahri"},
    {id:3,name:"Akali"},
    {id:4,name:"Alistar"},
    {id:5,name:"Amumu"},
    {id:6,name:"Anivia"},
    {id:7,name:"Annie"},
    {id:8,name:"Aphelios"},
    {id:9,name:"Ashe"},
    {id:10,name:"Aurelion Sol"},
    {id:11,name:"Azir"},
    {id:12,name:"Bardo"},
    {id:13,name:"Blitzcrank"},
    {id:14,name:"Brand"},
    {id:15,name:"Braum"},
    {id:16,name:"Caitlyn"},
    {id:17,name:"Camille"},
    {id:18,name:"Cassiopeia"},
    {id:19,name:"Cho'Gath"},
    {id:20,name:"Corki"},
    {id:21,name:"Darius"},
    {id:22,name:"Diana"},
    {id:23,name:"Dr. Mundo"},
    {id:24,name:"Draven"},
    {id:25,name:"Ekko"},
    {id:26,name:"Elise"},
    {id:27,name:"Evelynn"},
    {id:28,name:"Ezreal"},
    {id:29,name:"Fiddlesticks"},
    {id:30,name:"Fiora"},
    {id:31,name:"Fizz"},
    {id:32,name:"Galio"},
    {id:33,name:"Gangplank"},
    {id:34,name:"Garen"},
    {id:34,name:"Gnar"},
    {id:35,name:"Gragas"},
    {id:36,name:"Graves"},
    {id:37,name:"Gwen"},
    {id:38,name:"Hecarim"},
    {id:39,name:"Heimerdinger"},
    {id:40,name:"Illaoi"},
    {id:41,name:"Irelia"},
    {id:42,name:"Ivern"},
    {id:43,name:"Janna"},
    {id:44,name:"Jarvan IV"},
    {id:45,name:"Jax"},
    {id:46,name:"Jayce"},
    {id:47,name:"Jhin"},
    {id:48,name:"Jinx"},
    {id:49,name:"Kai'Sa"},
    {id:50,name:"Kalista"},   
    {id:51,name:"Karma"},
    {id:52,name:"Karthus"},
    {id:53,name:"Kassadin"},
    {id:54,name:"Katarina"},
    {id:55,name:"Kayle"},
    {id:56,name:"Kayn"},
    {id:57,name:"Kennen"},
    {id:58,name:"Kha'Zix"},
    {id:59,name:"Kindred"},
    {id:60,name:"Kled"},
    {id:61 ,name:"Kog'Maw"},
    {id:62 ,name:"LeBlanc"},
    {id:63 ,name:"Lee Sin"},
    {id:64 ,name:"Leona"},
    {id:65 ,name:"Lillia"},
    {id:66 ,name:"Lissandra"},
    {id:67 ,name:"Lucian"},
    {id:68 ,name:"Lulu"},
    {id:69 ,name:"Lux"},
    {id:70 ,name:"Maestro Yi"},
    {id:71 ,name:"Malphite"},
    {id:72 ,name:"Malzahar"},
    {id:74 ,name:"Maokai"},
    {id:75 ,name:"Miss Fortune"},
    {id:76 ,name:"Mordekaiser"},
    {id:77 ,name:"Morgana"},
    {id:78 ,name:"Nami"},
    {id:79 ,name:"Nasus"},
    {id:80 ,name:"Nautilus"},
    {id:81 ,name:"Neeko"},
    {id:82 ,name:"Nidalee"},
    {id:83 ,name:"Nocturne"},
    {id:84 ,name:"Nunu y Willump"},
    {id:85 ,name:"Olaf"},
    {id:86 ,name:"Orianna"},
    {id:87 ,name:"Ornn"},
    {id:88 ,name:"Pantheon"},
    {id:89 ,name:"Poppy"},
    {id:90 ,name:"Pyke"},
    {id:91 ,name:"Qiyana"},
    {id:92 ,name:"Quinn"},
    {id:93 ,name:"Rakan"},
    {id:94 ,name:"Rammus"},
    {id:95 ,name:"Rek'Sai"},
    {id:96 ,name:"Rell"},
    {id:97 ,name:"Renekton"},
    {id:98 ,name:"Rengar"},
    {id:99 ,name:"Riven"},
    {id:100 ,name:"Rumble"},
    {id:101 ,name:"Ryze"},
    {id:102 ,name:"Samira"},
    {id:103 ,name:"Sejuani"},
    {id:104 ,name:"Senna"},
    {id:105 ,name:"Seraphine"},
    {id:106 ,name:"Shaco"},
    {id:107 ,name:"Shen"},
    {id:108 ,name:"Shyvana"},
    {id:109 ,name:"Singed"},
    {id:110 ,name:"Sion"},
    {id:111 ,name:"Sivir"},
    {id:112 ,name:"Skarner"},
    {id:113 ,name:"Sona"},
    {id:114 ,name:"Soraka"},
    {id:115 ,name:"Swain"},
    {id:116 ,name:"Sylas"},
    {id:117 ,name:"Syndra"},
    {id:118 ,name:"Tahm Kench"},
    {id:119 ,name:"Taliyah"},
    {id:120 ,name:"Talon"},
    {id:121 ,name:"Taric"},
    {id:122 ,name:"Teemo"},
    {id:123 ,name:"Thresh"},
    {id:124 ,name:"Tristana"},
    {id:125 ,name:"Trundle"},
    {id:126 ,name:"Tryndamere"},
    {id:127 ,name:"Twisted Fate"},
    {id:128 ,name:"Twitch"},
    {id:129 ,name:"Udyr"},
    {id:130 ,name:"Urgot"},
    {id:131 ,name:"Varus"},
    {id:132 ,name:"Vayne"},
    {id:133 ,name:"Veigar"},
    {id:134 ,name:"Vel'Koz"},
    {id:135,name:"Vi"},
    {id:136 ,name:"Viego"},
    {id:137 ,name:"Viktor"},
    {id:138 ,name:"Vladimir"},
    {id:139 ,name:"Volibear"},
    {id:140 ,name:"Warwick"},
    {id:141 ,name:"Wukong"},
    {id:142 ,name:"Xayah"},
    {id:143 ,name:"Xerath"},
    {id:144 ,name:"Xin Zhao"},
    {id:145 ,name:"Yasuo"},
    {id:146 ,name:"Yone"},
    {id:147 ,name:"Yorick"},
    {id:148 ,name:"Yuumi"},
    {id:149 ,name:"Zac"},
    {id:150 ,name:"Zed"},
    {id:151 ,name:"Ziggs"},
    {id:152 ,name:"Zilean"},
    {id:153 ,name:"Zoe"},
    {id:154 ,name:"Zyra"},
    
]